stages:
    - build


build-job:
    tags:
        - test
    stage: build
    script:
        - echo "Hello, me"
        - whoami
        - ls 
        - mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
        - ssh-keyscan -H 10.9.8.25 >> ~/.ssh/known_hosts
        - ssh-keyscan -H 10.9.8.28 >> ~/.ssh/known_hosts
        - ssh-keyscan -H 10.9.8.26 >> ~/.ssh/known_hosts
        - ansible-playbook -i hostlist.txt ansible.yml
        - ssh 10.9.8.25
        - ping 10.0.0.2