---
- name: Install curl
  hosts: h1
  become: yes
  tasks:
    - name: update pck
      apt:
        update_cache: yes
        force: yes
        cache_valid_time: 36000
    - name: apt curl
      apt: name=curl state=latest
- name: Write interfaces
  hosts: h1
  vars:
    addr: 10.0.1.1
    other_subnet: 10.0.2.0
    router_addr: 10.0.1.2
  become: yes
  tasks:
    - name: Set interfaces
      template:
        src: template
        dest: /etc/network/interfaces.d/eth1
    - name: Set interfaces
      ansible.builtin.shell: |
        sudo ifdown eth1 && sudo ifup eth1
