---
- name: Install curl
  hosts: h1
  become: yes
  tasks:
    - name: update pck
      apt:
        update_cache: yes
        force: yes
        cache_valid_time: 36000
    - name: apt curl
      apt: name=curl state=latest
- name: Write interfaces
  hosts: h1
  tasks:
    - name: set interfaces
      ansible.builtin.shell: |
        sudo echo '
        source /etc/network/interfaces.d/*
        allow-hotplug eth0
        auto lo
        iface lo inet loopback
        iface eth0 inet dhcp
        dns-nameserver 8.8.8.8
        pre-up sleep 2

        auto eth1
        iface eth1 inet static
        	address 10.0.1.1
        	netmask 255.255.255.0
        up ip route add 10.0.2.0/24 via 10.0.1.2
        ' > /etc/network/interfaces
      become: yes