---
- name: install and start nginx
  hosts: h2
  become: yes
  vars:
    http_port: 80
  tasks:
  - name: update pck
    apt:
      update_cache: yes
      force: yes
      cache_valid_time: 36000
  - name: install nginx
    apt: name=nginx state=latest
  - name: start nginx
    service:
      name: nginx
      state: started
  - name: index.html is present
    ansible.builtin.template:
      src: index.html
      dest: /var/www/html/index.html
- name: Write interfaces
  hosts: h2
  vars:
    addr: 10.0.2.1
    other_subnet: 10.0.1.0
    router_addr: 10.0.2.2
  become: yes
  tasks:
    - name: Set interfaces
      template:
        src: template
        dest: /etc/network/interfaces.d/eth1
      - name: Set interfaces
      ansible.builtin.shell: |
        sudo ifdown eth1 && sudo ifup eth1
