---
- name: install and start nginx
  hosts: h2
  become: yes
  vars:
    http_port: 80
  tasks:
  - name: update pck
    apt:
      update_cache: yes
      force: yes
      cache_valid_time: 36000
  - name: install nginx
    apt: name=nginx state=latest
  - name: start nginx
    service:
      name: nginx
      state: started
  - name: index.html is present
    ansible.builtin.template:
      src: index.html
      dest: /var/www/html/index.html
- name: Write interfaces
  hosts: h2
  tasks:
    - name: Set interfaces
      ansible.builtin.shell: |
        sudo echo '
        source /etc/network/interfaces.d/*
        allow-hotplug eth0
        auto lo
        iface lo inet loopback
        iface eth0 inet dhcp
        dns-nameserver 8.8.8.8
        pre-up sleep 2

        auto eth1
        iface eth1 inet static
        	address 10.0.2.1
        	netmask 255.255.255.0
        up ip route add 10.0.1.0/24 via 10.0.2.2
        ' > /etc/network/interfaces
      become: yes