---
- name: Ip forwarding
  hosts: r1
  tasks:
    - ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes
      become: yes
- name: Write interfaces
  hosts: r1
  become: yes
  tasks:
    - name: Set interface 1
      vars:
        addr: 10.0.1.2
        ethnbr: 1
      template:
        src: templaterouter
        dest: /etc/network/interfaces.d/eth1
    - name: Set interface 2
      vars:
        addr: 10.0.2.2
        ethnbr: 2
      template:
        src: templaterouter
        dest: /etc/network/interfaces.d/eth2
    - name: Launch interfaces
      ansible.builtin.shell: |
        sudo ifdown eth1 && sudo ifup eth1
        sudo ifdown eth2 && sudo ifup eth2
